### ISSUE TITLE
Dirty / Touched / Visible fields should be tracked by bloom-forms

### ISSUE THREAD

**Issue by inkblotty** [vineyard-bloom/bloom-forms#12]
The redux store should tracked an array of touchedFields (received focus) and one of dirtyFields (fields changed) by their 'name' attribute.

Right now, `updateForm` and `manualFieldUpdate` both handle change events, so they can be altered for creating dirtyFields.

There are no `onFocus` events in each input yet to track.

**Comment by elvece** [comment]
NOTE: if typing (check on blur) hide error message
