### ISSUE TITLE
Select Input on Windows

### ISSUE THREAD

**Issue by LottA93** [vineyard-bloom/bloom-forms#80]
On Windows, whenever a user clicks away from the SelectInput, the SelectInput's onBlur event doesn't fire.

Also, the SelectInput won't re-open if I click in the typeahead or dropdown trigger when a value has been already been selected and it has kept focus.

**Comment by inkblotty** [comment]
Cannot reproduce onBlur bug -- tested on Windows machine (Edge and Chrome) and dropdowns always close onBlur (both typeahead and non-typeahead versions).

Clicking on input not reopening the dropdown was still occurring but is fixed.
